// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DragProgress: typeof import('./src/components/DragProgress.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElectronVersions: typeof import('./src/components/ElectronVersions.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    NSearch: typeof import('./src/components/n-search.vue')['default']
    ReactiveCounter: typeof import('./src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./src/components/ReactiveHash.vue')['default']
    SearchPanel: typeof import('./src/components/searchPanel.vue')['default']
  }
}

export { }
